site_title: "Ceremonias de Rapé"
site_description: "Descubre la sabiduría milenaria del rapé amazónico. Productos auténticos y ceremonias sagradas para tu crecimiento espiritual."
contact_email: "ceremonias@rape.com"
contact_phone: "+54 9 11 1234-5678"
contact_address: "Buenos Aires, Argentina"
