# Backend para producción en Netlify
backend:
  name: git-gateway
  branch: main

# Configuración para modo local - activar para desarrollo
local_backend: true

# Configura donde están los archivos de media
media_folder: "public/images"
public_folder: "/images"

# Configuración de contenido
collections:
  # Productos de Rapé
  - name: "productos"
    label: "Productos"
    folder: "content/productos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre del Producto", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Precio", name: "price", widget: "number" }
      - { label: "Disponible", name: "available", widget: "boolean", default: true }
      - { label: "Imagen Principal", name: "image", widget: "image", required: false }
      - { label: "Descripción Corta", name: "excerpt", widget: "text" }
      - { label: "Descripción Completa", name: "body", widget: "markdown" }
      - { label: "Tribu de Origen", name: "tribe", widget: "string", required: false }
      - { label: "Región", name: "region", widget: "string", required: false }
      - { label: "Peso (gramos)", name: "weight", widget: "number", required: false }
      - { label: "Fecha de Publicación", name: "date", widget: "datetime" }

  # Ceremonias
  - name: "ceremonias"
    label: "Ceremonias"
    folder: "content/ceremonias"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título de la Ceremonia", name: "title", widget: "string" }
      - { label: "Fecha y Hora", name: "date", widget: "datetime" }
      - { label: "Duración (horas)", name: "duration", widget: "number", default: 3 }
      - { label: "Ubicación", name: "location", widget: "string" }
      - { label: "Precio", name: "price", widget: "number" }
      - { label: "Cupos Disponibles", name: "capacity", widget: "number" }
      - { label: "Está Activa", name: "active", widget: "boolean", default: true }
      - { label: "Imagen", name: "image", widget: "image", required: false }
      - { label: "Descripción", name: "body", widget: "markdown" }
      - { label: "Facilitador", name: "facilitator", widget: "string", required: false }
      - { label: "Nivel", name: "level", widget: "select", options: ["Principiante", "Intermedio", "Avanzado", "Todos los niveles"] }

  # Blog/Noticias
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha de Publicación", name: "date", widget: "datetime" }
      - { label: "Autor", name: "author", widget: "string", default: "Ceremonias de Rapé" }
      - { label: "Imagen Destacada", name: "featured_image", widget: "image", required: false }
      - { label: "Extracto", name: "excerpt", widget: "text" }
      - { label: "Contenido", name: "body", widget: "markdown" }
      - { label: "Publicado", name: "published", widget: "boolean", default: true }
